# Generated by Django 4.2.7 on 2024-03-31 14:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_service', '0012_alter_city_id_alter_contact_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_Man',
            new_name='Service_provider',
        ),
    ]
