# Generated by Django 4.2.7 on 2024-04-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0014_rename_total_man_total_service_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
