# Generated by Django 4.2.7 on 2024-04-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0015_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
